//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.file.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pIdentCutoff",
    "queryCoveragCutoff",
    "evalueRatioCutoff"
})
@XmlRootElement(name = "CutoffSet")
public class CutoffSet {

    @XmlAttribute(name = "rank", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rank;
    @XmlElement(required = true)
    protected PIdentCutoff pIdentCutoff;
    @XmlElement(name = "QueryCoveragCutoff", required = true)
    protected QueryCoveragCutoff queryCoveragCutoff;
    @XmlElement(name = "EvalueRatioCutoff", required = true)
    protected EvalueRatioCutoff evalueRatioCutoff;

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the pIdentCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link PIdentCutoff }
     *     
     */
    public PIdentCutoff getPIdentCutoff() {
        return pIdentCutoff;
    }

    /**
     * Sets the value of the pIdentCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIdentCutoff }
     *     
     */
    public void setPIdentCutoff(PIdentCutoff value) {
        this.pIdentCutoff = value;
    }

    /**
     * Gets the value of the queryCoveragCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link QueryCoveragCutoff }
     *     
     */
    public QueryCoveragCutoff getQueryCoveragCutoff() {
        return queryCoveragCutoff;
    }

    /**
     * Sets the value of the queryCoveragCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryCoveragCutoff }
     *     
     */
    public void setQueryCoveragCutoff(QueryCoveragCutoff value) {
        this.queryCoveragCutoff = value;
    }

    /**
     * Gets the value of the evalueRatioCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link EvalueRatioCutoff }
     *     
     */
    public EvalueRatioCutoff getEvalueRatioCutoff() {
        return evalueRatioCutoff;
    }

    /**
     * Sets the value of the evalueRatioCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvalueRatioCutoff }
     *     
     */
    public void setEvalueRatioCutoff(EvalueRatioCutoff value) {
        this.evalueRatioCutoff = value;
    }

}
