//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.properties.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
/**
 * Taxonomic Unit Identification Tool (TUIT) is a free open source platform independent
 * software for accurate taxonomic classification of nucleotide sequences.
 * Copyright (C) 2013  Alexander Tuzhikov, Alexander Panchin and Valery Shestopalov.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * 
 */
@SuppressWarnings("WeakerAccess")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "database",
    "expect",
    "entrezQuery",
    "remote",
    "maxFilesInBatch"
})
@XmlRootElement(name = "BLASTNParameters")
public class BLASTNParameters {

    @XmlElement(name = "Database")
    protected List<Database> database;
    @XmlElement(name = "Expect", required = true)
    protected Expect expect;
    @XmlElement(name = "EntrezQuery", required = true)
    protected EntrezQuery entrezQuery;
    @XmlElement(name = "Remote", required = true)
    protected Remote remote;
    @XmlElement(name = "MaxFilesInBatch", required = true)
    protected MaxFilesInBatch maxFilesInBatch;

    /**
     * Gets the value of the database property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the database property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Database }
     * 
     * 
     */
    public List<Database> getDatabase() {
        if (database == null) {
            database = new ArrayList<Database>();
        }
        return this.database;
    }

    /**
     * Gets the value of the expect property.
     * 
     * @return
     *     possible object is
     *     {@link Expect }
     *     
     */
    public Expect getExpect() {
        return expect;
    }

    /**
     * Sets the value of the expect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expect }
     *     
     */
    public void setExpect(Expect value) {
        this.expect = value;
    }

    /**
     * Gets the value of the entrezQuery property.
     * 
     * @return
     *     possible object is
     *     {@link EntrezQuery }
     *     
     */
    public EntrezQuery getEntrezQuery() {
        return entrezQuery;
    }

    /**
     * Sets the value of the entrezQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntrezQuery }
     *     
     */
    public void setEntrezQuery(EntrezQuery value) {
        this.entrezQuery = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Remote }
     *     
     */
    public Remote getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Remote }
     *     
     */
    public void setRemote(Remote value) {
        this.remote = value;
    }

    /**
     * Gets the value of the maxFilesInBatch property.
     * 
     * @return
     *     possible object is
     *     {@link MaxFilesInBatch }
     *     
     */
    public MaxFilesInBatch getMaxFilesInBatch() {
        return maxFilesInBatch;
    }

    /**
     * Sets the value of the maxFilesInBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxFilesInBatch }
     *     
     */
    public void setMaxFilesInBatch(MaxFilesInBatch value) {
        this.maxFilesInBatch = value;
    }

}
