//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 04:56:14 PM EST 
//


package io.properties.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "database",
    "expect",
    "entrezQuery",
    "remote",
    "numThreads",
    "maxFilesInBatch",
    "keepBLASTOuts"
})
@XmlRootElement(name = "BLASTNParameters")
public class BLASTNParameters {

    @XmlElement(name = "Database")
    protected List<Database> database;
    @XmlElement(name = "Expect", required = true)
    protected Expect expect;
    @XmlElement(name = "EntrezQuery", required = true)
    protected EntrezQuery entrezQuery;
    @XmlElement(name = "Remote", required = true)
    protected Remote remote;
    @XmlElement(name = "NumThreads", required = true)
    protected NumThreads numThreads;
    @XmlElement(name = "MaxFilesInBatch", required = true)
    protected MaxFilesInBatch maxFilesInBatch;
    @XmlElement(name = "KeepBLASTOuts", required = true)
    protected KeepBLASTOuts keepBLASTOuts;

    /**
     * Gets the value of the database property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the database property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Database }
     * 
     * 
     */
    public List<Database> getDatabase() {
        if (database == null) {
            database = new ArrayList<Database>();
        }
        return this.database;
    }

    /**
     * Gets the value of the expect property.
     * 
     * @return
     *     possible object is
     *     {@link Expect }
     *     
     */
    public Expect getExpect() {
        return expect;
    }

    /**
     * Sets the value of the expect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expect }
     *     
     */
    public void setExpect(Expect value) {
        this.expect = value;
    }

    /**
     * Gets the value of the entrezQuery property.
     * 
     * @return
     *     possible object is
     *     {@link EntrezQuery }
     *     
     */
    public EntrezQuery getEntrezQuery() {
        return entrezQuery;
    }

    /**
     * Sets the value of the entrezQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntrezQuery }
     *     
     */
    public void setEntrezQuery(EntrezQuery value) {
        this.entrezQuery = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Remote }
     *     
     */
    public Remote getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Remote }
     *     
     */
    public void setRemote(Remote value) {
        this.remote = value;
    }

    /**
     * Gets the value of the numThreads property.
     * 
     * @return
     *     possible object is
     *     {@link NumThreads }
     *     
     */
    public NumThreads getNumThreads() {
        return numThreads;
    }

    /**
     * Sets the value of the numThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumThreads }
     *     
     */
    public void setNumThreads(NumThreads value) {
        this.numThreads = value;
    }

    /**
     * Gets the value of the maxFilesInBatch property.
     * 
     * @return
     *     possible object is
     *     {@link MaxFilesInBatch }
     *     
     */
    public MaxFilesInBatch getMaxFilesInBatch() {
        return maxFilesInBatch;
    }

    /**
     * Sets the value of the maxFilesInBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxFilesInBatch }
     *     
     */
    public void setMaxFilesInBatch(MaxFilesInBatch value) {
        this.maxFilesInBatch = value;
    }

    /**
     * Gets the value of the keepBLASTOuts property.
     * 
     * @return
     *     possible object is
     *     {@link KeepBLASTOuts }
     *     
     */
    public KeepBLASTOuts getKeepBLASTOuts() {
        return keepBLASTOuts;
    }

    /**
     * Sets the value of the keepBLASTOuts property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeepBLASTOuts }
     *     
     */
    public void setKeepBLASTOuts(KeepBLASTOuts value) {
        this.keepBLASTOuts = value;
    }

}
