//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
/**
 * Taxonomic Unit Identification Tool (TUIT) is a free open source platform independent
 * software for accurate taxonomic classification of nucleotide sequences.
 * Copyright (C) 2013  Alexander Tuzhikov, Alexander Panchin and Valery Shestopalov.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * 
 */
@SuppressWarnings("WeakerAccess")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pIdentCutoff",
    "queryCoverageCutoff",
    "evalueRatioCutoff"
})
@XmlRootElement(name = "CutoffSet")
public class CutoffSet {

    @XmlAttribute(name = "rank", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rank;
    @XmlElement(required = true)
    protected PIdentCutoff pIdentCutoff;
    @XmlElement(name = "QueryCoverageCutoff", required = true)
    protected QueryCoverageCutoff queryCoverageCutoff;
    @XmlElement(name = "EvalueRatioCutoff", required = true)
    protected EvalueRatioCutoff evalueRatioCutoff;

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the pIdentCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link PIdentCutoff }
     *     
     */
    public PIdentCutoff getPIdentCutoff() {
        return pIdentCutoff;
    }

    /**
     * Sets the value of the pIdentCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIdentCutoff }
     *     
     */
    public void setPIdentCutoff(PIdentCutoff value) {
        this.pIdentCutoff = value;
    }

    /**
     * Gets the value of the queryCoverageCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link QueryCoverageCutoff }
     *     
     */
    public QueryCoverageCutoff getQueryCoverageCutoff() {
        return queryCoverageCutoff;
    }

    /**
     * Sets the value of the queryCoverageCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryCoverageCutoff }
     *     
     */
    public void setQueryCoverageCutoff(QueryCoverageCutoff value) {
        this.queryCoverageCutoff = value;
    }

    /**
     * Gets the value of the evalueRatioCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link EvalueRatioCutoff }
     *     
     */
    public EvalueRatioCutoff getEvalueRatioCutoff() {
        return evalueRatioCutoff;
    }

    /**
     * Sets the value of the evalueRatioCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvalueRatioCutoff }
     *     
     */
    public void setEvalueRatioCutoff(EvalueRatioCutoff value) {
        this.evalueRatioCutoff = value;
    }

}
