//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.properties.jaxb;

import javax.xml.bind.annotation.XmlRegistry;
/**
 * Taxonomic Unit Identification Tool (TUIT) is a free open source platform independent
 * software for accurate taxonomic classification of nucleotide sequences.
 * Copyright (C) 2013  Alexander Tuzhikov, Alexander Panchin and Valery Shestopalov.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TUITProperties }
     * 
     */
    public TUITProperties createTUITProperties() {
        return new TUITProperties();
    }

    /**
     * Create an instance of {@link DBConnection }
     * 
     */
    public DBConnection createDBConnection() {
        return new DBConnection();
    }

    /**
     * Create an instance of {@link BLASTNPath }
     * 
     */
    public BLASTNPath createBLASTNPath() {
        return new BLASTNPath();
    }

    /**
     * Create an instance of {@link TMPDir }
     * 
     */
    public TMPDir createTMPDir() {
        return new TMPDir();
    }

    /**
     * Create an instance of {@link BLASTNParameters }
     * 
     */
    public BLASTNParameters createBLASTNParameters() {
        return new BLASTNParameters();
    }

    /**
     * Create an instance of {@link SpecificationParameters }
     * 
     */
    public SpecificationParameters createSpecificationParameters() {
        return new SpecificationParameters();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link EntrezQuery }
     * 
     */
    public EntrezQuery createEntrezQuery() {
        return new EntrezQuery();
    }

    /**
     * Create an instance of {@link CutoffSet }
     * 
     */
    public CutoffSet createCutoffSet() {
        return new CutoffSet();
    }

    /**
     * Create an instance of {@link PIdentCutoff }
     * 
     */
    public PIdentCutoff createPIdentCutoff() {
        return new PIdentCutoff();
    }

    /**
     * Create an instance of {@link QueryCoverageCutoff }
     * 
     */
    public QueryCoverageCutoff createQueryCoverageCutoff() {
        return new QueryCoverageCutoff();
    }

    /**
     * Create an instance of {@link EvalueRatioCutoff }
     * 
     */
    public EvalueRatioCutoff createEvalueRatioCutoff() {
        return new EvalueRatioCutoff();
    }

    /**
     * Create an instance of {@link Expect }
     * 
     */
    public Expect createExpect() {
        return new Expect();
    }

    /**
     * Create an instance of {@link Remote }
     * 
     */
    public Remote createRemote() {
        return new Remote();
    }

    /**
     * Create an instance of {@link MaxFilesInBatch }
     * 
     */
    public MaxFilesInBatch createMaxFilesInBatch() {
        return new MaxFilesInBatch();
    }

}
