//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.file.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cutoffSet"
})
@XmlRootElement(name = "SpecificationParameters")
public class SpecificationParameters {

    @XmlElement(name = "CutoffSet", required = true)
    protected CutoffSet cutoffSet;

    /**
     * Gets the value of the cutoffSet property.
     * 
     * @return
     *     possible object is
     *     {@link CutoffSet }
     *     
     */
    public CutoffSet getCutoffSet() {
        return cutoffSet;
    }

    /**
     * Sets the value of the cutoffSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutoffSet }
     *     
     */
    public void setCutoffSet(CutoffSet value) {
        this.cutoffSet = value;
    }

}
