//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 12:20:55 PM MSK 
//


package io.file.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbConnection",
    "blastnPath",
    "tmpDir",
    "blastnParameters",
    "specificationParameters"
})
@XmlRootElement(name = "TUITProperties")
public class TUITProperties {

    @XmlElement(name = "DBConnection", required = true)
    protected DBConnection dbConnection;
    @XmlElement(name = "BLASTNPath", required = true)
    protected BLASTNPath blastnPath;
    @XmlElement(name = "TMPDir", required = true)
    protected TMPDir tmpDir;
    @XmlElement(name = "BLASTNParameters", required = true)
    protected BLASTNParameters blastnParameters;
    @XmlElement(name = "SpecificationParameters")
    protected List<SpecificationParameters> specificationParameters;

    /**
     * Gets the value of the dbConnection property.
     * 
     * @return
     *     possible object is
     *     {@link DBConnection }
     *     
     */
    public DBConnection getDBConnection() {
        return dbConnection;
    }

    /**
     * Sets the value of the dbConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBConnection }
     *     
     */
    public void setDBConnection(DBConnection value) {
        this.dbConnection = value;
    }

    /**
     * Gets the value of the blastnPath property.
     * 
     * @return
     *     possible object is
     *     {@link BLASTNPath }
     *     
     */
    public BLASTNPath getBLASTNPath() {
        return blastnPath;
    }

    /**
     * Sets the value of the blastnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLASTNPath }
     *     
     */
    public void setBLASTNPath(BLASTNPath value) {
        this.blastnPath = value;
    }

    /**
     * Gets the value of the tmpDir property.
     * 
     * @return
     *     possible object is
     *     {@link TMPDir }
     *     
     */
    public TMPDir getTMPDir() {
        return tmpDir;
    }

    /**
     * Sets the value of the tmpDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMPDir }
     *     
     */
    public void setTMPDir(TMPDir value) {
        this.tmpDir = value;
    }

    /**
     * Gets the value of the blastnParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BLASTNParameters }
     *     
     */
    public BLASTNParameters getBLASTNParameters() {
        return blastnParameters;
    }

    /**
     * Sets the value of the blastnParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLASTNParameters }
     *     
     */
    public void setBLASTNParameters(BLASTNParameters value) {
        this.blastnParameters = value;
    }

    /**
     * Gets the value of the specificationParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificationParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificationParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecificationParameters }
     * 
     * 
     */
    public List<SpecificationParameters> getSpecificationParameters() {
        if (specificationParameters == null) {
            specificationParameters = new ArrayList<SpecificationParameters>();
        }
        return this.specificationParameters;
    }

}
